name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        subdir: [cdk, api, ui]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm ci
      working-directory: ${{ matrix.subdir }}
    - run: npm run build --if-present
      working-directory: ${{ matrix.subdir }}
    - run: npm test
      working-directory: ${{ matrix.subdir }}
