name: Build 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    # build api
    - run: npm ci
      working-directory: api
    - run: npm run build --if-present
      working-directory: api
    - run: npm test
      working-directory: api
    # build ui
    - run: npm ci
      working-directory: ui
    - run: npm run build --if-present
      working-directory: ui
    - run: npm test
      working-directory: ui
    # build cdk
    - run: npm ci
      working-directory: cdk
    - run: npm run build --if-present
      working-directory: cdk
    - run: npm test
      working-directory: cdk
